dist: focal
language: minimal
sudo: required
install: true
before_install:
  - sudo apt-get install -y ca-certificates-java ca-certificates wget openjdk-11-jdk-headless npm
#  - sudo npm install -g @appthreat/cdxgen
#  - sudo npm install -g license-compatibility-checker
addons:
  sonarcloud:
    organization: "hack23"
  apt:
    update: true    
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
services:
  - docker
script:
  - npm install
  - npm run audit-dependencies
  - npm run audit-licenses
#  - npm run license-check || true
  - npm clean-install-test
  - npm run lint
  - sonar-scanner
